### ISSUE TITLE
Sự kiện

### ISSUE THREAD

**Issue by wasimodo98** [webtsgroup/LT-Monastery#3]
Muốn tìm = barcode được không
Nhập người tham gia = máy quét barcode thì làm thế nào

**Comment by wasimodo98** [comment]
![image](https://user-images.githubusercontent.com/20689057/30518692-7fc47f1c-9baf-11e7-84f1-89a05819f100.png)
Chỗ này nên làm danh sách hay hơn, còn cái add làm riêng ra, có thể add = barcode(máy scan barcode, hoặc đánh tên hoặc đánh id

**Comment by webtsgroup** [comment]
cái này OK rồi
